django/apps/web_copo/urls.py
from django.conf.urls import patterns, url

from apps.web_copo import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^testing/', views.view_test, name='test'),
                       url(r'^testing2/', views.view_test2, name='test'),
                       url(r'^login/', views.copo_login, name='login'),
                       url(r'^logout/', views.copo_logout, name='logout'),
                       url(r'^register/', views.copo_register, name='register'),
                       url(r'^new_profile/', views.new_profile, name='new_bundle'),
                       url(r'^profile/(?P<profile_id>\d+)/view', views.view_profile, name='view_profile'),
                       url(r'^new_collection/', views.new_collection, name='new_collection'),
                       url(r'^collection/(?P<collection_id>\d+)/view', views.view_collection, name='view_collection'),
)

django/project_copo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from rest_framework import routers

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project_copo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^copo/', include('apps.web_copo.urls', namespace='copo')),
    url(r'^rest/', include('apps.web_copo.rest_urls', namespace='rest')),
)

django/apps/web_copo/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
import datetime
from time import time
from django.core.files.storage import FileSystemStorage
from chunked_upload.models import ChunkedUpload

fs = FileSystemStorage(location='/Users/fshaw/Desktop/test')


def get_upload_file_name(instance, filename):
    return 'uploaded_files/%s_%s' % (str(time()).replace('.', '_'), filename)


# profile is the top level container object representing a profile of work
class Profile(models.Model):
    title = models.CharField(max_length=500)
    abstract = models.TextField(null=True, blank=True)
    abstract_short = models.CharField(max_length=150, null=True, blank=True)
    date_created = models.DateField(default=datetime.date.today)
    date_modified = models.DateField(default=datetime.date.today)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.title


#collection represents a type of data i.e. ENA, GenBank, pdf, image data, movie etc.
class Collection(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50, default="custom submission")
    profile = models.ForeignKey(Profile)

    def __unicode__(self):
        return self.name


#resource is a object which represents raw data as either a file path or a url
class Resource(models.Model):
    name = models.CharField(max_length=50)
    URL = models.CharField(max_length=200, null=True, blank=True)
    path = models.CharField(max_length=200, null=True, blank=True)
    md5_checksum = models.CharField(max_length=200, null=True, blank=True)
    collection = models.ForeignKey(Collection)

    def __unicode__(self):
        return self.name


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )


class Document(models.Model):
    docfile = models.FileField(upload_to='/Users/fshaw/Desktop/test')

    @classmethod
    def create(cls, file, location):
        doc = cls(docfile=file)
        doc.docfile.upload_to = location

        return doc


#the following ENA objects are self explanatory
class EnaStudy(models.Model):
    collection = models.ForeignKey(Collection)
    study_title = models.CharField(max_length=1000)
    study_type = models.CharField(max_length=5000)
    study_abstract = models.TextField(null=True, blank=True)
    center_name = models.CharField(max_length=100, null=True, blank=True)
    center_project_name = models.CharField(max_length=100, null=True, blank=True)
    study_description = models.CharField(max_length=5000, null=True, blank=True)

    def __unicode__(self):
        return self.study_title


class EnaStudyAttr(models.Model):
    ena_study = models.ForeignKey(EnaStudy)
    tag = models.CharField(max_length=50)
    value = models.CharField(max_length=50)
    unit = models.CharField(max_length=50, null=True, blank=True)

    def __unicode__(self):
        return self.tag


class EnaSample(models.Model):
    ena_study = models.ForeignKey(EnaStudy)
    title = models.CharField(max_length=50, null=True, blank=True)
    taxon_id = models.IntegerField()
    scientific_name = models.CharField(max_length=50, null=True, blank=True)
    common_name = models.CharField(max_length=50, null=True, blank=True)
    anonymized_name = models.CharField(max_length=50, null=True, blank=True)
    individual_name = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)


class EnaSampleAttr(models.Model):
    ena_sample = models.ForeignKey(EnaSample)
    tag = models.CharField(max_length=50)
    value = models.CharField(max_length=50)
    unit = models.CharField(max_length=50, null=True, blank=True)


class EnaExperiment(models.Model):
    study = models.ForeignKey(EnaStudy, null=True)
    sample = models.ForeignKey(EnaSample, null=True)
    platform = models.CharField(max_length=50, null=True, blank=True)
    instrument = models.CharField(max_length=50, null=True, blank=True)
    lib_name = models.CharField(max_length=50, null=True, blank=True)
    lib_source = models.CharField(max_length=50, null=True, blank=True)
    lib_selection = models.CharField(max_length=50, null=True, blank=True)
    lib_strategy = models.CharField(max_length=50, null=True, blank=True)
    insert_size = models.IntegerField(default=0, null=True, blank=True)
    design_description = models.CharField(max_length=50, null=True, blank=True)
    lib_construction_protocol = models.CharField(max_length=50, null=True, blank=True)
    lib_layout = models.CharField(max_length=50, null=True, blank=True)
    file_type = models.CharField(max_length=50, null=True, blank=True)
    lib_name = models.CharField(max_length=100, null=True, blank=True)
    #panel id allows for multiple experiments to be displayed as if they were multiplexed
    #single experiments. i.e. make a new panel for each new panel id
    panel_ordering = models.IntegerField(default=0)
    panel_id = models.CharField(max_length=100, null=True, blank=True)
    data_modal_id = models.CharField(max_length=100, null=True, blank=True)


class ExpFile(models.Model):
    #class to join experiments with files
    experiment = models.ForeignKey(EnaExperiment)
    file = models.ForeignKey(ChunkedUpload)
    md5_hash = models.CharField(max_length=50, null=True, blank=True)

django/apps/web_copo/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext

from apps.web_copo.models import Collection, Profile, EnaStudy, EnaSample


# Create your views here.
# @login_required
def index(request):
    username = User(username=request.user)
    # c = Collection.objects.filter(user = username)
    study_set = Profile.objects.all()
    context = {'user': request.user, 'studies': study_set}
    return render(request, 'copo/index.html', context)


def try_login_with_orcid_id(request):
    username = request.POST['frm_login_username']
    password = request.POST[('frm_login_password')]

    # try to log into orchid
    return HttpResponse('1')


def copo_login(request):
    # pdb.set_trace()
    if request.method == 'GET':
        print 'running get'
        return render(request, 'copo/login.html')

    else:

        username = request.POST['frm_login_username']
        password = request.POST['frm_login_password']

        if not (username or password):
            return HttpResponseRedirect('/copo/login')
        else:
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)

                    return HttpResponseRedirect('/copo/')

                    # Return a 'disabled account' error message

            # Return an 'invalid login' error message.

            return render(request, 'copo/login.html')


def copo_logout(request):
    logout(request)
    return render(request, 'copo/login.html')


def copo_register(request):
    if request.method == 'GET':
        return render(request, 'copo/register.html')
    else:
        # create user and return to login page
        firstname = request.POST['frm_register_firstname']
        lastname = request.POST['frm_register_lastname']
        email = request.POST['frm_register_email']
        username = request.POST['frm_register_username']
        password = request.POST['frm_register_password']

        user = User.objects.create_user(username, email, password)
        user.set_password(password)
        user.last_name = lastname
        user.first_name = firstname
        user.save()

        return render(request, 'copo/login.html')


def new_profile(request):
    if request.method == 'POST':
        # get current user
        u = User.objects.get(username=request.user)
        a = request.POST['study_abstract']
        sa = a[:147]
        sa += '...'
        ti = request.POST['study_title']
        s = Profile(title=ti, user=u, abstract=a, abstract_short=sa)
        s.save()
        return HttpResponseRedirect('/copo/')


def view_profile(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    collections = Collection.objects.filter(profile__id=profile_id)
    context = {'profile_id': profile_id, 'profile_title': profile.title, 'profile_abstract': profile.abstract_short,
               'collections': collections}
    return render(request, 'copo/profile.html', context)


def view_test(request):
    context = {}
    return render(request, 'copo/testing.html', context)


def new_collection(request):
    c_type = request.POST['collection_type']
    c_name = request.POST['collection_name']
    profile_id = request.POST['profile_id']
    b = Profile.objects.get(id=profile_id)

    c = b.collection_set.create(
        name=c_name,
        type=c_type
    )

    context = {'request_type': c_type, 'bundle': b}
    return HttpResponseRedirect(reverse('copo:view_profile', kwargs={'profile_id': profile_id}))


def view_collection(request, collection_id):
    # collection = Collection.objects.get(id=pk)
    collection = get_object_or_404(Collection, pk=collection_id)
    #get profile id for breadcrumb
    profile_id = collection.profile.id
    #check type of collection
    if collection.type == 'ENA Submission':
        #get samples for enastudy association
        try:
            study = EnaStudy.objects.get(collection__id=int(collection_id))
            samples = EnaSample.objects.filter(ena_study__id=study.id)
            data_dict = {'collection': collection, 'samples': samples, 'collection_id': collection_id,
                         'study_id': study.id, 'profile_id': profile_id}
            return render_to_response('copo/ena_collection_multi.html', data_dict,
                                      context_instance=RequestContext(request))
        except ObjectDoesNotExist as e:
            data_dict = {'collection': collection, 'collection_id': collection_id, 'profile_id': profile_id}
            return render(request, 'copo/ena_collection_multi.html', data_dict,
                          context_instance=RequestContext(request))


def view_test2(request):
    return render(request, 'copo/testing2.html')

django/apps/web_copo/templates/copo/base.html
<!DOCTYPE html>
<meta charset="utf-8">
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Default Page Title{% endblock %}</title>


	{% block stylesheet_block %}{% endblock %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'copo/css/bootstrap/bootstrap.css' %}">
    <!--<link rel="stylesheet" href="{% static 'copo/css/bootstrap/bootstrap-theme.css' %}">-->
    <link rel="stylesheet" href="{% static 'copo/css/copo/style.css' %}">


    <link rel="shortcut icon" href="{% static 'copo/img/dna_orange.png' %}"/>

    <!-- Font Awesome -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>

    <!-- Additional stylesheets -->


    <script src="{% static 'copo/js/jquery.js' %}"></script>
    <script src="{% static 'copo/js/jquery.cookie.js' %}"></script>
    <script src="{% static 'copo/js/serialize_form_json.js' %}"></script>
    <script src="{% static 'copo/js/bootstrap.js' %}"></script>
    <!-- Additional javascripts -->
    {% block js_block %}{% endblock %}


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="container">

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="row header">
                <div class="col-sm-7 col-md-7 col-lg-7">
                    <div id="site_brand">
                        <h2 class="h2">COPO
                            <small>Colaborative Plant Omics</small>
                        </h2>
                    </div>

                </div>
                <div class="col-sm-5 col-md-5 col-lg-5">
                    <div id="profile_header">
                        <a href="">
								<span class="settings_icon">
									<i class="fa fa-cog fa-lg"></i>
								</span>
                        </a>
                        <a href="">{{ user }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3 col-md-3 col-lg-3">
            <div id="sidebar">
                <ul class="nav nav-pills nav-stacked sidebar_text">
                    <li class="active">
                        <a>
                            <i class="fa fa-list fa"></i>
                            <span class="icon_text">Profiles</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="fa fa-area-chart"></i>
                            <span class="icon_text">Accessions</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="fa fa-file-o"></i>
                            <span class="icon_text">Publications</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="fa fa-link"></i>
                            <span class="icon_text">References</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-sm-9 col-md-9 col-lg-9">

            <div class="row">

                <div class="col-sm-4 col-md-4 col-lg-4">
                    <div id="browse_header">
                        {% block breadcrumb_block %}{% endblock %}
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4"></div>
                <div class="col-sm-4 col-md-4 col-lg-4">
                    {% block browse_header_block %} default search {% endblock %}
                </div>

            </div>

            <div class="row work_area">

                {% block work_area %} <h2 class="h2">DEFAULT CONTENT AREA</h2> {% endblock %}

            </div>

        </div>
        <div class="col-sm-2 col-md-2 col-lg-2"></div>
    </div>
</div>

</body>
</html>

django/apps/web_copo/templates/copo/index.html
{% extends 'copo/base.html' %}

{% load staticfiles %}

{% block stylesheet_block %}
<link rel="stylesheet" href="{% static 'copo/css/copo/browse_style.css' %}">

{% endblock %}


{% block title_block %} Index {% endblock %}

{% block tagline_block %}


{% endblock %}


{% block breadcrumb_block %}
<ol class="breadcrumb">
    <li class="active"><a href="{% url 'copo:index' %}">Home</a></li>

</ol>
{% endblock %}

{% block browse_header_block %}

<div id="browse_header">
        <span class="blue_icon">
           <a><i class="fa fa-plus-circle" data-toggle="modal" data-target="#newStudyModal"></i></a>
        </span>
        <span class="blue_icon">
            <a><i class="fa fa-pencil-square-o"></i></a>
        </span>
        <span class="blue_icon">
            <a><i class="fa fa-trash-o"></i></a>
        </span>

    <div class="input-group input-group-sm">
            <span class="input-group-addon">
                <i class="fa fa-search"></i>
            </span>
        <input type="search" class="form-control" placeholder="Search">
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="newStudyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">New Profile</h4>
            </div>
            <div class="modal-body">

                <form role="form" action="/copo/new_profile/" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="study_title">Title</label>
                        <input type="text" class="form-control" name="study_title" placeholder="Enter Collection Name">
                    </div>
                    <div class="form-group">
                        <label for="study_abstract">Abstract</label>
                        <textarea rows="6" class="form-control" name="study_abstract"
                                  placeholder="Enter Abstract"></textarea>
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>

            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block work_area %}

<h2 class="h2">Work Profiles</h2>

<table class="browse_table">

    <tr>
        <th style="opacity: 0"></th>
        <th>Title</th>
        <th>Abstract</th>
        <th>Date</th>
    </tr>


    {% for s in studies %}
    <tr>
        <td style="text-align: center">
            <a href="{% url 'copo:view_profile' profile_id=s.id %}"><i class="fa fa-pencil-square-o "></i></a>
        </td>
        <td>{{ s.title }}</td>
        <td>{{ s.abstract_short }}</td>
        <td>{{ s.date }}</td>
    </tr>
    {% endfor %}

</table>


{% endblock %}


{% block js_block %}
<script src="{% static 'copo/js/index.js' %}"></script>
{% endblock %}

django/apps/web_copo/templates/copo/login.html
{% extends 'copo/base.html' %}
{% load staticfiles %}
{% block js_block %}
<script src="{% static 'copo/js/copo.login_view.js' %}"></script>
{% endblock %}

{% block title_block %} Login {% endblock %}

{% block tagline_block %} Please login {% endblock %}

{% block main_block %}


<div class="generic-form">
    <form method="post" action="/copo/login/">
        {% csrf_token %}

        <input type="text" id="frm_login_username" name="frm_login_username" placeholder="Name"/>

        <input type="password" id="frm_login_password" name="frm_login_password" placeholder="Password"/>
        <button class="submit" id="frm_login_submit">Submit</button>
    </form>
    <span style="float: right; margin-top:10px"><a href="/copo/register/">Register</a></span>
</div>


{% endblock %}

django/apps/web_copo/templates/copo/profile.html
{% extends 'copo/base.html' %}

{% load staticfiles %}

{% block stylesheet_block %}
<link rel="stylesheet" href="{% static 'copo/css/copo/browse_style.css' %}">
<link rel="stylesheet" href="{% static 'copo/css/copo/study.css' %}">

{% endblock %}


{% block title_block %} Study {% endblock %}

{% block tagline_block %}{% endblock %}

{% block breadcrumb_block %}
<ol class="breadcrumb">
    <li><a href="{% url 'copo:index' %}">Home</a></li>
    <li class="active"><a href="{% url 'copo:view_profile' profile_id=profile_id %}">Profile</a></li>
</ol>
{% endblock %}


{% block browse_header_block %}

<div id="browse_header">
        <span class="blue_icon">
           <a><i class="fa fa-plus-circle" data-toggle="modal" data-target="#newStudyModal"></i></a>
        </span>
        <span class="blue_icon">
            <a><i class="fa fa-pencil-square-o"></i></a>
        </span>
        <span class="blue_icon">
            <a><i class="fa fa-trash-o"></i></a>
        </span>

    <div class="input-group input-group-sm">
            <span class="input-group-addon">
                <i class="fa fa-search"></i>
            </span>
        <input type="search" class="form-control" placeholder="Search">
    </div>
</div>

{% endblock %}

{% block work_area %}

<!-- here is the markup for the top table data pulled in from the study itself -->
<table class="browse_table">
    <h2 class="h2">{{ profile_title }}</h2>
    <hr/>
    <h3>Collections</h3>
    <tr>
        <th>Name</th>
        <th>Type</th>
    </tr>

    {% for c in collections %}

    <tr>
        <td><a href="{% url 'copo:view_collection' collection_id=c.id %}">{{ c.name }}</a></td>

        <td>{{ c.type }}</td>
    </tr>

    {% endfor %}

</table>

<!-- subsequently we should loop and have some sort of collapsable table showing the existing work collections -->


<!-- then we have a button to add a new work collection -->
<div class="text-center add_data_button">
    <button type="button" class="btn btn-primary btn-lg text-center" data-toggle="modal"
            data-target="#newCollectionModal">Add Collection
    </button>
</div>


<!-- here is the hidden modal which will be populated from js, will look at having a rest call to a python service to
query the forms xml for the type of data selected by the user -->

<!-- Modal -->
<div class="modal fade" id="newCollectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">New Collection</h4>
            </div>
            <div class="modal-body">

                <form role="form" id="ena_study_form" action="/copo/new_collection/" method="post">
                    {% csrf_token %}

                    <input type="hidden" name="profile_id" value="{{ profile_id }}">

                    <div class="form-group">
                        <label for="collection_name">Collection Name</label><br/>
                        <input type="text" name="collection_name" id="collection_name" class="form_control"
                               placeholder="Enter Name"/>
                    </div>


                    <div class="form-group">
                        <label for="collection_type">Colection Type</label>
                        <select name="collection_type" id="collection_type" class="form-control">
                            <option>ENA Submission</option>
                            <option>PDF File</option>
                            <option>Image</option>
                            <option>Movie</option>
                            <option>Other</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>

                </form>

            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block js_block %}

{% endblock %}

django/apps/web_copo/templates/copo/register.html
{% extends 'copo/base.html' %}
{% load staticfiles %}
{% block js_block %}
<script src="{% static 'copo/js/copo.login_view.js' %}"></script>
{% endblock %}

{% block title_block %} Register {% endblock %}

{% block tagline_block %} Enter your details {% endblock %}

{% block main_block %}


<div class="generic-form">
    <form method="post" action="copo/register/">
        {% csrf_token %}

        <input type="text" id="frm_register_firstname" name="frm_register_firstname" placeholder="First Name"/>
        <input type="text" id="frm_register_lastname" name="frm_register_lastname" placeholder="Last Name"/>
        <input type="text" id="frm_register_email" name="frm_register_email" placeholder="Email Address"/>
        <input type="text" id="frm_register_username" name="frm_register_username" placeholder="Username"/>
        <input type="password" id="frm_register_password" name="frm_register_password" placeholder="Password"/>
        <input type="password" id="frm_register_password_repeat" name="frm_register_password_repeat"
               placeholder="Repeat Password"/>

        <button class="submit" id="frm_login_submit">Submit</button>
    </form>
    <span style="float: right; margin-top:10px"><a href="copo/register/">Register</a></span>
</div>


{% endblock %}

django/apps/web_copo/templates/copo/testing.html
{% extends 'copo/base.html' %}

{% load staticfiles %}

{% block stylesheet_block %}
<link rel="stylesheet" href="{% static 'copo/css/copo/browse_style.css' %}">
<link rel="stylesheet" href="{% static 'copo/css/copo/study.css' %}">
<link rel="stylesheet" href="{% static 'copo/css/uploader/jquery.fileupload.css' %}">

{% endblock %}


{% block title_block %} Study {% endblock %}

{% block tagline_block %}{% endblock %}

{% block breadcrumb_block %}

{% endblock %}


{% block browse_header_block %}

<div id="browse_header">
        <span class="blue_icon">
           <a><i class="fa fa-plus-circle" data-toggle="modal" data-target="#newStudyModal"></i></a>
        </span>
        <span class="blue_icon">
            <a><i class="fa fa-pencil-square-o"></i></a>
        </span>
        <span class="blue_icon">
            <a><i class="fa fa-trash-o"></i></a>
        </span>

    <div class="input-group input-group-sm">
            <span class="input-group-addon">
                <i class="fa fa-search"></i>
            </span>
        <input type="search" class="form-control" placeholder="Search">
    </div>
</div>

{% endblock %}

{% block work_area %}


        <input type="button" name="file_input"/>
        <script>
            $('input[type=button]').click(function(){
            	console.log(this);
            })
        </script>


{% endblock %}


{% block js_block %}
<script src="{% static 'copo/js/bootstrap-datepicker.js' %}"></script>

<script src="{% static 'copo/js/uploader/vendor/jquery.ui.widget.js'%}"></script>
<script src="{% static 'copo/js/uploader/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'copo/js/uploader/jquery.fileupload.js' %}"></script>
<script src="{% static 'copo/js/uploader/main.js' %}"></script>
<script src="{% static 'copo/js/spark-md5.js' %}"></script>
{% endblock %}